name: Deploy to Elastic Beanstalk

on:
  push:
    branches: [ main ]
    paths:
      - 'Dockerfile'
      - 'requirements.txt'
      - 'src/**'
      - '**.py'
      - '.github/workflows/deploy.yml'
  workflow_dispatch:

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      IMAGE_URI: ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}
      EB_APP_NAME: ${{ secrets.EB_APP_NAME }}
      EB_ENV_NAME: ${{ secrets.EB_ENV_NAME }}
      EB_S3_BUCKET: ${{ secrets.EB_S3_BUCKET }}
      AWS_REGION: ${{ secrets.AWS_REGION }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}
          role-session-name: gh-${{ github.run_id }}

      - name: Verify AWS identity
        run: aws sts get-caller-identity

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Compute unique version label
        run: |
          echo "LABEL=v${GITHUB_RUN_NUMBER}" >> $GITHUB_ENV
          echo "Using EB version label: v${GITHUB_RUN_NUMBER}"

      - name: Build & Push Docker image (linux/amd64)
        run: |
          docker buildx build \
            --platform linux/amd64 \
            -t "${IMAGE_URI}:latest" \
            -t "${IMAGE_URI}:${LABEL}" \
            --push .

      - name: Create Dockerrun.aws.json
        run: |
          cat > Dockerrun.aws.json <<'JSON'
          {
            "AWSEBDockerrunVersion": "1",
            "Image": {
              "Name": "${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}:latest",
              "Update": "true"
            },
            "Ports": [
              { "ContainerPort": "8080" }
            ],
            "Logging": "/var/log/nginx"
          }
          JSON

      - name: Zip Dockerrun
        run: zip -r "deploy-${LABEL}.zip" Dockerrun.aws.json

      - name: Upload bundle to S3
        run: |
          BUNDLE_KEY="ci/${GITHUB_REPOSITORY#*/}/deploy-${LABEL}.zip"
          aws s3 cp "deploy-${LABEL}.zip" "s3://${EB_S3_BUCKET}/${BUNDLE_KEY}"
          echo "BUNDLE_KEY=${BUNDLE_KEY}" >> $GITHUB_ENV

      - name: Create EB Application Version
        run: |
          set -e
          TIMESTAMP=$(date +%Y%m%d%H%M%S)

          UNIQUE_LABEL="${LABEL}-${TIMESTAMP}-${GITHUB_RUN_NUMBER}-${GITHUB_RUN_ATTEMPT}"
          echo "UNIQUE_LABEL=${UNIQUE_LABEL}" >> $GITHUB_ENV
          
          if aws elasticbeanstalk describe-application-versions \
              --application-name "${EB_APP_NAME}" \
              --version-labels "${UNIQUE_LABEL}" \
              --query 'ApplicationVersions[0].VersionLabel' \
              --output text 2>/dev/null | grep -q "${UNIQUE_LABEL}"; then
            echo "Warning: Version ${UNIQUE_LABEL} already exists, appending random suffix"
            UNIQUE_LABEL="${UNIQUE_LABEL}-$(openssl rand -hex 4)"
            echo "UNIQUE_LABEL=${UNIQUE_LABEL}" >> $GITHUB_ENV
          fi
          
          aws elasticbeanstalk create-application-version \
            --application-name "${EB_APP_NAME}" \
            --version-label "${UNIQUE_LABEL}" \
            --source-bundle "S3Bucket=${EB_S3_BUCKET},S3Key=${BUNDLE_KEY}"
          
      - name: Update EB Environment
        run: |
          aws elasticbeanstalk update-environment \
            --environment-name "${EB_ENV_NAME}" \
            --version-label "${UNIQUE_LABEL}"

      - name: Update EB Environment
        run: |
          aws elasticbeanstalk update-environment \
            --environment-name "${EB_ENV_NAME}" \
            --version-label "${LABEL}"